on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1
      - name: Install dependencies
        run: npm install    
      - name: Generate build
        run: npm run build
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    # We specify that deploys needs to
    # finish before we create a release
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
      - name: Zip build
        uses: thedoctor0/zip-release@master
        with:
          filename: react-github-actions-release-build.zip
          path: react-github-actions-build
      - name: Upload build zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-release-build.zip
          path: react-github-actions-release-build.zip
      - name: Releae with notes
        uses: softprops/action-gh-release@v1
        with:
          files: react-github-actions-release-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: react-github-actions-release-build.zip
      #     token: ${{ secrets.GITHUB_TOKEN }} # Available by default